name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
    #branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag typescript-onvif-cctv:$(date +%s)
